version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    restart: always

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
    ports:
      - "3001:3000"  # Web UI
      - "222:22"     # SSH (optional)
    restart: always
