name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies + ESLint
        run: |
          cd web
          npm install
          npm install eslint --save-dev

      - name: Fix eslint permission & run scan
        run: |
          cd web
          chmod +x ./node_modules/.bin/eslint
          npx eslint .

      - name: Start web server and test UI
        run: |
          cd web
          nohup npm start & sleep 5
          curl --fail http://localhost:3000 || (echo "Web app not reachable" && exit 1)
